work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
#  window_size: 150
  data_path: /public/home/wangchy5/CPR/Skeleton/CPR_Skeleton/st-gcn/resource/Processed_Data/train.npy # CPR  DATA
  label_path: /public/home/wangchy5/CPR/Skeleton/CPR_Skeleton/st-gcn/resource/Processed_Data/train_label.npy
test_feeder_args:
  data_path: /public/home/wangchy5/CPR/Skeleton/CPR_Skeleton/st-gcn/resource/Processed_Data/test.npy
  label_path: /public/home/wangchy5/CPR/Skeleton/CPR_Skeleton/st-gcn/resource/Processed_Data/test_label.npy

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 5
  edge_importance_weighting: True
  graph_args:
    layout: 'cpr_skeleton'
    strategy: 'spatial'

# training
device: [0]
batch_size: 256
test_batch_size: 256

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



